sudo: true
dist: trusty
addons:
  sonarcloud:
# See https://docs.travis-ci.com/user/sonarcloud/
    organization: "dstrelak-github"
    token:
        secure: $SONAR_TOKEN

script: 
 - pushd module1 && build-wrapper-linux-x86-64 --out-dir ../bw-outputs/module1/ ./build.sh
 - popd
 - pushd module2 && build-wrapper-linux-x86-64 --out-dir ../bw-outputs/module2/ ./build.sh
 - popd
 - sonar-scanner
