sudo: true
dist: trusty
addons:
  sonarcloud:
# See https://docs.travis-ci.com/user/sonarcloud/
    organization: "dstrelak-github"
    token:
        secure: $SONAR_TOKEN

script: 
 - pushd sonarqube-scanner-build-wrapper-linux/src/module1 && build-wrapper-linux-x86-64 --out-dir bw-outputs ./build.sh
 - popd
 - pushd sonarqube-scanner-build-wrapper-linux/src/module2 && build-wrapper-linux-x86-64 --out-dir bw-outputs ./build.sh
 - popd
 - sonar-scanner
