sudo: true
dist: trusty
addons:
  sonarcloud:
# See https://docs.travis-ci.com/user/sonarcloud/
    organization: "dstrelak-github"
    token:
        secure: $SONAR_TOKEN
before_install:
 - cd sonarqube-scanner-build-wrapper-linux
script: 
 - build-wrapper-linux-x86-64 --out-dir bw-outputs ./build.sh
 - sonar-scanner
